### PR TITLE
Allows a string of '0' to pass as a valid replacement.

### PR DESCRIPTION
**Pull request by jesseschutt**
I ran into a situation where the string '0' was being interpreted as falsey and wasn't being replaced properly. This PR addresses that.

### CODE REVIEW

**Comment by jesseschutt** [comment]
Hello, just checking in to see the status of this PR. Thanks!

**Comment by HollyIT** [comment]
Sorry for the delay. Been getting ready to go out of town. This looks good and I've merged it.

**Comment by jesseschutt** [comment]
> Sorry for the delay. Been getting ready to go out of town. This looks good and I've merged it.

Hi Jamie - Thanks for looking at this PR! 

I'm afraid a lot has changed since I originally opened it back in March. You may want to roll it back here on your repository because it has modified quite a bit from your original package. I actually forked it and [released it with my changes](https://packagist.org/packages/jesseschutt/token-replacer) (attribution is still in place).

If you do want to keep my changes I would suggest tagging a completely new version to not break existing apps.

Thanks!

**Comment by HollyIT** [comment]
@jesseschutt - thanks. I just reverted it.

**Pull request merged**
